# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('UK', 'UK'), ('England', 'England'), ('Wales', 'Wales'), ('Scotland', 'Scotland')], max_length=100)),
                ('month_season', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December'), ('SUM', 'Summer'), ('WIN', 'Winter'), ('SPR', 'Spring'), ('AUT', 'Autumn'), ('ANN', 'Annual')], max_length=3)),
                ('year', models.IntegerField()),
                ('value_type', models.CharField(choices=[('MIN', 'Minimum Temperature((Degrees C)'), ('MAX', 'Maximum Temperature((Degrees C)'), ('MEAN', 'Mean Temperature((Degrees C)'), ('SUNSHINE', 'Sunshine (Total hours)'), ('RAINFALL', 'Rainfall (mm)')], max_length=100)),
                ('value', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'WeatherData',
                'verbose_name_plural': 'WeatherDatas',
            },
        ),
    ]
